FROM maven:3.9.9-eclipse-temurin-21-alpine
WORKDIR /app

# Cache dependencies
COPY pom.xml .
RUN mvn dependency:go-offline -q

# Copy source
COPY src ./src

# Run spring boot with devtools
CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.profiles=docker", "-q"]
