### 

@base_url = http://localhost:8080
@delivery_id = 1
@jwt_token = <your_token_here>
@order_id = 1


### Get Delivery by Order

# @name get_delivery

GET {{base_url}}/api/deliveries/order/{{place_order.response.body.id}} HTTP/1.1
Authorization: Bearer {{jwt_token}}


### Update Delivery Status

PUT {{base_url}}/api/deliveries/{{get_delivery.response.body.id}}/status HTTP/1.1
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
  "status": "DELIVERED"
}
